name: SpeechCraft
main: de.Keyle.SpeechCraft
version: 0.0.1
author: The Bukkit Team
description: A language API for Bukkit plugins.
commands:
  lang:
    description: Set your language.
    usage: /<command> <language>